version: '3.8'
services:
  app:
    image: hellow
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"
networks:
  default:
    external:
      name: dev-network
